apiVersion: apps/v1
kind: Deployment
metadata:
  name: linebot
  namespace: linebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linebot
  template:
    metadata:
      labels:
        app: linebot
    spec:
      containers:
      - name: linebot
        image: line-bot-my-bunny-buddy_linebot:latest
        ports:
        - containerPort: 5500
        env:
        - name: CHANNEL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: linebot-secret
              key: CHANNEL_ACCESS_TOKEN
        - name: CHANNEL_SECRET
          valueFrom:
            secretKeyRef:
              name: linebot-secret
              key: CHANNEL_SECRET
        - name: AI_PROVIDER
          valueFrom:
            secretKeyRef:
              name: linebot-secret
              key: AI_PROVIDER
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: linebot-secret
              key: GEMINI_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: linebot-secret
              key: OPENAI_API_KEY
        - name: GOOGLE_APPLICATION_CREDENTIALS_JSON
          valueFrom:
            secretKeyRef:
              name: linebot-secret
              key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        - name: CWA_API_KEY
          valueFrom:
            secretKeyRef:
              name: linebot-secret
              key: CWA_API_KEY
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: linebot-secret
              key: PORT