apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linebot-ingress
  namespace: linebot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: lineapi.minibot.com.tw
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: linebot-service
            port:
              number: 80