apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kubectl
    image: lachlanevenson/k8s-kubectl:latest
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache gettext jq && cat
    tty: true